# Generated by Django 4.2.27 on 2026-01-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('susceptibility', 'Susceptibility'), ('resilience', 'Resilience')], max_length=20)),
                ('dem', models.BooleanField(default=True)),
                ('rainfall', models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Heavy', 'Heavy'), ('Extreme', 'Extreme')], max_length=10)),
                ('is_soil', models.BooleanField(default=False)),
                ('is_drainage', models.BooleanField(default=False)),
                ('agent', models.CharField(blank=True, choices=[('Pedestrian', 'Pedestrian'), ('Vehicle', 'Vehicle')], max_length=20, null=True)),
                ('map_url', models.URLField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
