# Generated by Django 4.2.27 on 2026-01-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_floodscenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodscenario',
            name='confidence_map',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
