# Generated by Django 4.2.27 on 2026-01-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_floodscenario_confidence_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='stats',
        ),
    ]
