# Generated by Django 4.2.27 on 2026-02-21 12:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0004_remove_scenario_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodPatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('barangay_name', models.CharField(db_index=True, max_length=255)),
                ('depth', models.FloatField()),
                ('confidence', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='GMMPartitionScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('susceptibility', 'Susceptibility'), ('resiliency', 'Resiliency')], default='susceptibility', max_length=20)),
                ('agent', models.CharField(blank=True, choices=[('Pedestrian', 'Pedestrian'), ('Vehicle', 'Vehicle')], default=None, max_length=20, null=True)),
                ('dem', models.BooleanField(default=True)),
                ('is_soil', models.BooleanField(default=False)),
                ('is_drainage', models.BooleanField(default=False)),
                ('map_url', models.URLField(blank=True, null=True)),
                ('tif_file', models.FileField(blank=True, null=True, upload_to='flood_tifs/')),
                ('rainfall_scenario', models.CharField(choices=[('SCS-style front-loaded', 'SCS-style front-loaded'), ('SCS-style back-loaded', 'SCS-style back-loaded'), ('SCS-style balanced', 'SCS-style balanced'), ('Chicago-style Triangular', 'Chicago-style Triangular')], max_length=100)),
                ('is_land_use', models.BooleanField(default=True)),
                ('is_infiltration', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GMMQuadrantScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('susceptibility', 'Susceptibility'), ('resiliency', 'Resiliency')], default='susceptibility', max_length=20)),
                ('agent', models.CharField(blank=True, choices=[('Pedestrian', 'Pedestrian'), ('Vehicle', 'Vehicle')], default=None, max_length=20, null=True)),
                ('dem', models.BooleanField(default=True)),
                ('is_soil', models.BooleanField(default=False)),
                ('is_drainage', models.BooleanField(default=False)),
                ('map_url', models.URLField(blank=True, null=True)),
                ('tif_file', models.FileField(blank=True, null=True, upload_to='flood_tifs/')),
                ('rainfall', models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Heavy', 'Heavy'), ('Extreme', 'Extreme')], max_length=100)),
                ('is_land_use', models.BooleanField(default=False)),
                ('is_infiltration', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManilaPartitionScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('susceptibility', 'Susceptibility'), ('resiliency', 'Resiliency')], default='susceptibility', max_length=20)),
                ('agent', models.CharField(blank=True, choices=[('Pedestrian', 'Pedestrian'), ('Vehicle', 'Vehicle')], default=None, max_length=20, null=True)),
                ('dem', models.BooleanField(default=True)),
                ('is_soil', models.BooleanField(default=False)),
                ('is_drainage', models.BooleanField(default=False)),
                ('map_url', models.URLField(blank=True, null=True)),
                ('tif_file', models.FileField(blank=True, null=True, upload_to='flood_tifs/')),
                ('rainfall_scenario', models.CharField(choices=[('SCS-style front-loaded', 'SCS-style front-loaded'), ('SCS-style back-loaded', 'SCS-style back-loaded'), ('SCS-style balanced', 'SCS-style balanced'), ('Chicago-style Triangular', 'Chicago-style Triangular')], max_length=100)),
                ('is_land_use', models.BooleanField(default=False)),
                ('is_infiltration', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManilaQuadrantScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('susceptibility', 'Susceptibility'), ('resiliency', 'Resiliency')], default='susceptibility', max_length=20)),
                ('agent', models.CharField(blank=True, choices=[('Pedestrian', 'Pedestrian'), ('Vehicle', 'Vehicle')], default=None, max_length=20, null=True)),
                ('dem', models.BooleanField(default=True)),
                ('is_soil', models.BooleanField(default=False)),
                ('is_drainage', models.BooleanField(default=False)),
                ('map_url', models.URLField(blank=True, null=True)),
                ('tif_file', models.FileField(blank=True, null=True, upload_to='flood_tifs/')),
                ('rainfall', models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Heavy', 'Heavy'), ('Extreme', 'Extreme')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FloodScenario',
        ),
        migrations.DeleteModel(
            name='Scenario',
        ),
    ]
