# Generated by Django 4.2.27 on 2026-03-01 07:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_floodpatch_gmmpartitionscenario_gmmquadrantscenario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('water_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='rivers/')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
    ]
