# Generated by Django 4.2.27 on 2026-03-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_waterbody'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodpatch',
            name='psgc_code',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
