# Generated by Django 4.2.27 on 2026-03-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_floodpatch_psgc_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmmpartitionscenario',
            name='depth_limit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gmmpartitionscenario',
            name='triangular_peak',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gmmpartitionscenario',
            name='rainfall_scenario',
            field=models.CharField(choices=[('front-loaded', 'SCS-style front-loaded'), ('back-loaded', 'SCS-style back-loaded'), ('balanced', 'SCS-style balanced'), ('triangular', 'Chicago-style Triangular')], max_length=100),
        ),
    ]
