# Generated by Django 6.0.3 on 2026-03-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_gmmpartitionscenario_depth_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodpatch',
            name='poverty',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
