# Generated by Django 6.0.3 on 2026-03-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_floodpatch_poverty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floodpatch',
            name='poverty',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
