# Generated by Django 6.0.3 on 2026-03-31 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_floodpatch_poverty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GMMQuadrantScenario',
        ),
        migrations.DeleteModel(
            name='ManilaPartitionScenario',
        ),
        migrations.DeleteModel(
            name='ManilaQuadrantScenario',
        ),
        migrations.RemoveField(
            model_name='gmmpartitionscenario',
            name='is_drainage',
        ),
        migrations.RemoveField(
            model_name='gmmpartitionscenario',
            name='is_soil',
        ),
    ]
