from django.http import FileResponse
import io
import math
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter
from reportlab.lib.utils import ImageReader
from pathlib import Path
from PIL import Image
import rasterio
import numpy as np
import requests
from rasterio.warp import reproject, Resampling
from rasterio.crs import CRS
from rasterio.transform import from_bounds

BASE_DIR = Path(__file__).resolve().parent

MAP_PX = 600  # pixel resolution for both layers


def deg2num(lat, lon, zoom):
    lat_r = math.radians(lat)
    n = 2 ** zoom
    x = (lon + 180.0) / 360.0 * n
    y = (1.0 - math.log(math.tan(lat_r) + 1 / math.cos(lat_r)) / math.pi) / 2.0 * n
    return x, y


def num2deg(xtile, ytile, zoom):
    n = 2 ** zoom
    lon = xtile / n * 360.0 - 180.0
    lat = math.degrees(math.atan(math.sinh(math.pi * (1 - 2 * ytile / n))))
    return lat, lon


def fetch_carto_basemap(lat, lon, zoom, width_px=MAP_PX, height_px=MAP_PX):
    """Fetches and stitches CartoDB tiles into a single basemap image."""

    def deg2tile(lat_deg, lon_deg, zoom):
        lat_r = math.radians(lat_deg)
        n = 2 ** zoom
        x = int((lon_deg + 180.0) / 360.0 * n)
        y = int((1.0 - math.log(math.tan(lat_r) + 1 / math.cos(lat_r)) / math.pi) / 2.0 * n)
        return x, y

    tile_size = 256
    tiles_x = math.ceil(width_px / tile_size) + 1
    tiles_y = math.ceil(height_px / tile_size) + 1

    center_tx, center_ty = deg2tile(lat, lon, zoom)
    start_tx = center_tx - tiles_x // 2
    start_ty = center_ty - tiles_y // 2

    canvas_img = Image.new("RGB", (tiles_x * tile_size, tiles_y * tile_size), (220, 220, 220))

    headers = {'User-Agent': 'Mozilla/5.0'}
    for i in range(tiles_x):
        for j in range(tiles_y):
            tx = start_tx + i
            ty = start_ty + j
            url = f"https://a.basemaps.cartocdn.com/light_all/{zoom}/{tx}/{ty}.png"
            try:
                resp = requests.get(url, headers=headers, timeout=5)
                if resp.status_code == 200:
                    tile = Image.open(io.BytesIO(resp.content)).convert("RGB")
                    canvas_img.paste(tile, (i * tile_size, j * tile_size))
            except Exception as e:
                print(f"Tile fetch error ({tx},{ty}): {e}")

    cx = (tiles_x * tile_size) // 2
    cy = (tiles_y * tile_size) // 2
    left = cx - width_px // 2
    top = cy - height_px // 2
    cropped = canvas_img.crop((left, top, left + width_px, top + height_px))
    return cropped


def get_basemap_bounds(lat, lon, zoom, width_px=MAP_PX):
    """Returns the geographic bounds (west, south, east, north) of the fetched basemap."""
    cx, cy = deg2num(lat, lon, zoom)
    half = width_px / 2 / 256  # half-width in tile units
    nw_lat, nw_lon = num2deg(cx - half, cy - half, zoom)
    se_lat, se_lon = num2deg(cx + half, cy + half, zoom)
    return nw_lon, se_lat, se_lon, nw_lat  # west, south, east, north


def create_pdf(request, scenario, map_type, map_path):
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    page_width, page_height = letter
    SIDE_MARGIN = 0.4 * inch

    legend_image = BASE_DIR / "media" / "legend.png"
    compass = BASE_DIR / "media" / "compass.png"
    daluyan_logo = BASE_DIR / "media" / "Daluyan_PH_Logo.png"

    # 1. Header Logo
    if daluyan_logo.exists():
        c.drawImage(ImageReader(str(daluyan_logo)),
                    SIDE_MARGIN, page_height - 0.9 * inch,
                    width=1.5 * inch, height=0.75 * inch,
                    preserveAspectRatio=True, mask='auto')

    # 2. Top Right Text
    c.setFont("Helvetica", 10)
    c.drawRightString(page_width - SIDE_MARGIN, page_height - 0.5 * inch, "Generated by DaluyanPH")

    # 3. Title
    c.setFont("Helvetica-Bold", 20)
    c.drawCentredString(page_width / 2, page_height - 1 * inch,
                        f"Flood Risk Map : {map_type.title()}")

    # --- Map Box ---
    map_width = 5.5 * inch
    map_height = 5.5 * inch
    map_x = (page_width - map_width) / 2
    map_y = page_height - map_height - 1.5 * inch

    # --- Basemap ---
    lat, lon, zoom = 14.5995, 120.9842, 13

    try:
        basemap_img = fetch_carto_basemap(lat, lon, zoom)
        c.drawImage(ImageReader(basemap_img),
                    map_x, map_y, width=map_width, height=map_height)
    except Exception as e:
        print(f"Basemap Error: {e}")
        c.setFillColorRGB(0.9, 0.9, 0.9)
        c.rect(map_x, map_y, map_width, map_height, fill=1, stroke=0)

    # --- Flood Overlay: warped to match basemap bounds exactly ---
    try:
        basemap_west, basemap_south, basemap_east, basemap_north = get_basemap_bounds(lat, lon, zoom)

        dst_crs = CRS.from_epsg(4326)
        dst_transform = from_bounds(basemap_west, basemap_south, basemap_east, basemap_north, MAP_PX, MAP_PX)

        with rasterio.open(map_path) as src:
            dst_data = np.zeros((MAP_PX, MAP_PX), dtype=src.dtypes[0])
            reproject(
                source=rasterio.band(src, 1),
                destination=dst_data,
                src_transform=src.transform,
                src_crs=src.crs,
                dst_transform=dst_transform,
                dst_crs=dst_crs,
                resampling=Resampling.nearest
            )

        rgba_data = np.zeros((MAP_PX, MAP_PX, 4), dtype=np.uint8)
        alpha_val = 180
        color_map = {
            0: [255, 255, 255, 0],          # No Flood: #FFFFFF (Set Alpha to 0 to make it fully transparent)
            1: [198, 219, 239, alpha_val],  # Light: #C6DBEF
            2: [107, 174, 214, alpha_val],  # Moderate: #6BAED6
            3: [33, 113, 181, alpha_val],   # Heavy: #2171B5
            4: [8, 48, 107, alpha_val]      # Extreme: #08306B
        }
        for val, color in color_map.items():
            rgba_data[dst_data == val] = color

        overlay_img = Image.fromarray(rgba_data, 'RGBA')
        c.drawImage(ImageReader(overlay_img),
            map_x + 0.2 * inch, map_y - 0.3 * inch, width=map_width, height=map_height,
            mask='auto')

    except Exception as e:
        print(f"Overlay Rendering Error: {e}")

    # --- Legend & Compass ---
    line_y = map_y - 0.4 * inch
    legend_w, legend_h = 1.2 * inch, 1.2 * inch
    compass_w, compass_h = 0.8 * inch, 0.8 * inch # Slightly smaller for balance
    
    # Y-coordinate: Placing them right above the separator line
    # We use line_y (the separator line) as the base
    bottom_element_y = line_y + 0.4 * inch 

    # 1. Legend: Lower Left (on top of the footer)
    if legend_image.exists():
        c.drawImage(
            ImageReader(str(legend_image)),
            SIDE_MARGIN,               # X: Align with left margin
            bottom_element_y,          # Y: Just above the line
            width=legend_w, 
            height=legend_h,
            preserveAspectRatio=True, 
            mask='auto'
        )

    # 2. Compass: Lower Right (on top of the footer)
    if compass.exists():
        c.drawImage(
            ImageReader(str(compass)),
            page_width - SIDE_MARGIN - compass_w, # X: Align with right margin
            bottom_element_y,                     # Y: Just above the line
            width=compass_w, 
            height=compass_h,
            preserveAspectRatio=True, 
            mask='auto'
        )
    # --- Separator Line ---
    line_y = map_y - 0.4 * inch
    c.line(SIDE_MARGIN, line_y, page_width - SIDE_MARGIN, line_y)

    # --- Footer Boxes ---
    gap = 0.25 * inch
    box_width = (page_width - (2 * SIDE_MARGIN) - gap) / 2
    box_height = 1.5 * inch
    box_y = line_y - box_height - 0.3 * inch

    c.rect(SIDE_MARGIN, box_y, box_width, box_height)
    c.rect(SIDE_MARGIN + box_width + gap, box_y, box_width, box_height)

    c.setFont("Helvetica-Bold", 10)
    c.setFillColorRGB(0, 0, 0)
    c.drawString(SIDE_MARGIN + 0.1 * inch, box_y + box_height - 0.2 * inch, "SCENARIO DETAILS")

    detail_y = box_y + box_height - 0.4 * inch
    c.setFont("Helvetica", 9)
    potential_details = [
        ("rainfall_scenario", "Rainfall Distribution"),
        ("depth_limit", "Rainfall Depth (mm)"),
        ("triangular_peak", "Peak Ratio"),
        ("agent", "User Type"),
    ]
    for attr, label in potential_details:
        if hasattr(scenario, attr):
            val = getattr(scenario, attr)
            if val is not None:
                c.drawString(SIDE_MARGIN + 0.1 * inch, detail_y, f"{label}: {val}")
                detail_y -= 0.15 * inch

    c.setFont("Helvetica-Bold", 10)
    c.drawString(SIDE_MARGIN + box_width + gap + 0.1 * inch,
                 box_y + box_height - 0.2 * inch, "RISK LEVEL SUMMARY")
    summary_x = SIDE_MARGIN + box_width + gap + 0.1 * inch
    
    # Inside Risk Level Summary Text
    c.setFont("Helvetica", 7)  # Smaller font to fit descriptions
    text_y = box_y + box_height - 0.4 * inch
    line_height = 0.12 * inch

    descriptions = [
        ("Light Flooding:", "Minor water accumulation on low-lying roads; most areas passable."),
        ("Medium Flooding:", "Noticeable and disruptive; potentially affecting ground-level areas."),
        ("Heavy Flooding:", "Significant and hazardous; roads difficult to pass; impact on infrastructure."),
        ("Extreme Flooding:", "Severe/widespread; movement dangerous; high potential for major damage.")
    ]

    for title, desc in descriptions:
        c.setFont("Helvetica-Bold", 7)
        c.drawString(summary_x, text_y, title)
        text_y -= line_height
        c.setFont("Helvetica", 6.5)
        c.drawString(summary_x + 0.05 * inch, text_y, desc)
        text_y -= (line_height + 0.02 * inch)

    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer