from django.http import FileResponse
import io
import math
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter
from reportlab.lib.utils import ImageReader
from pathlib import Path
from PIL import Image
import rasterio
import numpy as np
import requests
from rasterio.warp import reproject, Resampling
from rasterio.crs import CRS
from rasterio.transform import from_bounds
from django.db.models import Count
from api.models import FloodPatch
from api.utils.stats_helper import get_top_extreme_stats, calculate_area_sq_km

BASE_DIR = Path(__file__).resolve().parent

MAP_PX = 600  # pixel resolution for both layers


def deg2num(lat, lon, zoom):
    lat_r = math.radians(lat)
    n = 2 ** zoom
    x = (lon + 180.0) / 360.0 * n
    y = (1.0 - math.log(math.tan(lat_r) + 1 / math.cos(lat_r)) / math.pi) / 2.0 * n
    return x, y


def num2deg(xtile, ytile, zoom):
    n = 2 ** zoom
    lon = xtile / n * 360.0 - 180.0
    lat = math.degrees(math.atan(math.sinh(math.pi * (1 - 2 * ytile / n))))
    return lat, lon


def fetch_carto_basemap(lat, lon, zoom, width_px=MAP_PX, height_px=MAP_PX):
    """Fetches and stitches CartoDB tiles into a single basemap image."""

    def deg2tile(lat_deg, lon_deg, zoom):
        lat_r = math.radians(lat_deg)
        n = 2 ** zoom
        x = int((lon_deg + 180.0) / 360.0 * n)
        y = int((1.0 - math.log(math.tan(lat_r) + 1 / math.cos(lat_r)) / math.pi) / 2.0 * n)
        return x, y

    tile_size = 256
    tiles_x = math.ceil(width_px / tile_size) + 1
    tiles_y = math.ceil(height_px / tile_size) + 1

    center_tx, center_ty = deg2tile(lat, lon, zoom)
    start_tx = center_tx - tiles_x // 2
    start_ty = center_ty - tiles_y // 2

    canvas_img = Image.new("RGB", (tiles_x * tile_size, tiles_y * tile_size), (220, 220, 220))

    headers = {'User-Agent': 'Mozilla/5.0'}
    for i in range(tiles_x):
        for j in range(tiles_y):
            tx = start_tx + i
            ty = start_ty + j
            url = f"https://a.basemaps.cartocdn.com/light_all/{zoom}/{tx}/{ty}.png"
            try:
                resp = requests.get(url, headers=headers, timeout=5)
                if resp.status_code == 200:
                    tile = Image.open(io.BytesIO(resp.content)).convert("RGB")
                    canvas_img.paste(tile, (i * tile_size, j * tile_size))
            except Exception as e:
                print(f"Tile fetch error ({tx},{ty}): {e}")

    cx = (tiles_x * tile_size) // 2
    cy = (tiles_y * tile_size) // 2
    left = cx - width_px // 2
    top = cy - height_px // 2
    cropped = canvas_img.crop((left, top, left + width_px, top + height_px))
    return cropped


def get_basemap_bounds(lat, lon, zoom, width_px=MAP_PX):
    """Returns the geographic bounds (west, south, east, north) of the fetched basemap."""
    cx, cy = deg2num(lat, lon, zoom)
    half = width_px / 2 / 256  # half-width in tile units
    nw_lat, nw_lon = num2deg(cx - half, cy - half, zoom)
    se_lat, se_lon = num2deg(cx + half, cy + half, zoom)
    return nw_lon, se_lat, se_lon, nw_lat  # west, south, east, north


def create_res_pdf(request, scenario, map_type, map_path):
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    page_width, page_height = letter
    SIDE_MARGIN = 0.4 * inch

    legend_image = BASE_DIR / "media" / "legend_res.png"
    compass = BASE_DIR / "media" / "compass.png"
    daluyan_logo = BASE_DIR / "media" / "Daluyan_PH_Logo.png"

    # 1. Header Logo
    if daluyan_logo.exists():
        c.drawImage(ImageReader(str(daluyan_logo)),
                    SIDE_MARGIN, page_height - 0.9 * inch,
                    width=1.5 * inch, height=0.75 * inch,
                    preserveAspectRatio=True, mask='auto')

    # 2. Top Right Text
    c.setFont("Helvetica", 10)
    c.drawRightString(page_width - SIDE_MARGIN, page_height - 0.5 * inch, "Generated by DaluyanPH")

    # 3. Title
    c.setFont("Helvetica-Bold", 20)
    c.drawCentredString(page_width / 2, page_height - 1 * inch,
                        f"Flood Resiliency Map of Manila City")

    # --- Map Box ---
    map_width = 5.5 * inch
    map_height = 5.5 * inch
    map_x = (page_width - map_width) / 2
    map_y = page_height - map_height - 1.5 * inch

    # --- Basemap ---
    lat, lon, zoom = 14.5995, 120.9842, 13

    try:
        basemap_img = fetch_carto_basemap(lat, lon, zoom)
        c.drawImage(ImageReader(basemap_img),
                    map_x, map_y, width=map_width, height=map_height)
    except Exception as e:
        print(f"Basemap Error: {e}")
        c.setFillColorRGB(0.9, 0.9, 0.9)
        c.rect(map_x, map_y, map_width, map_height, fill=1, stroke=0)

    # --- Flood Overlay: warped to match basemap bounds exactly ---
    try:
        basemap_west, basemap_south, basemap_east, basemap_north = get_basemap_bounds(lat, lon, zoom)

        dst_crs = CRS.from_epsg(4326)
        dst_transform = from_bounds(basemap_west, basemap_south, basemap_east, basemap_north, MAP_PX, MAP_PX)

        with rasterio.open(map_path) as src:
            dst_data = np.zeros((MAP_PX, MAP_PX), dtype=src.dtypes[0])
            reproject(
                source=rasterio.band(src, 1),
                destination=dst_data,
                src_transform=src.transform,
                src_crs=src.crs,
                dst_transform=dst_transform,
                dst_crs=dst_crs,
                resampling=Resampling.nearest
            )

        rgba_data = np.zeros((MAP_PX, MAP_PX, 4), dtype=np.uint8)
        alpha_val = 180
        color_map = {
            0: [255, 255, 255, 0],           # Transparent
            1: [34, 197, 94, alpha_val],     # Low
            2: [249, 115, 22, alpha_val],    # Moderate
            3: [150, 22, 32, alpha_val],     # High
        }
        rgba_data = np.zeros((MAP_PX, MAP_PX, 4), dtype=np.uint8)
        for val, color in color_map.items():
            rgba_data[dst_data == val] = color

        overlay_img = Image.fromarray(rgba_data, 'RGBA')
        c.drawImage(ImageReader(overlay_img),
                    map_x + 0.2 * inch, map_y - 0.3 * inch, width=map_width, height=map_height,
                    mask='auto')

    except Exception as e:
        print(f"Overlay Rendering Error: {e}")

    # --- Legend & Compass (OVERLAY ON MAP) ---
    # Increase these values to make the legend bigger
    legend_w, legend_h = 2 * inch, 2 * inch 
    compass_w, compass_h = 1.0 * inch, 1.0 * inch

    # Legend position (bottom-left inside map)
    legend_x = map_x + 0.05 * inch

    # Subtract more from map_y to move it further down
    # For example, subtract 0.5 inches instead of 0.1
    legend_y = map_y - 0.45 * inch

    # FIXED: Compass position 
    # Instead of relying on the new, larger legend_w, 
    # we anchor the compass to a fixed coordinate relative to the map.
    compass_x = legend_x + 1.7 * inch # Changed from 'legend_x + legend_w + 0.2'
    compass_y = map_y + 0.15 * inch

    # Draw Legend
    if legend_image.exists():
        c.drawImage(
            ImageReader(str(legend_image)),
            legend_x,
            legend_y,
            width=legend_w,
            height=legend_h,
            preserveAspectRatio=True,
            mask='auto'
        )

    # Draw Compass
    if compass.exists():
        c.drawImage(
            ImageReader(str(compass)),
            compass_x,
            compass_y,
            width=compass_w,
            height=compass_h,
            preserveAspectRatio=True,
            mask='auto'
        )
    # --- Separator Line ---
    line_y = map_y - 0.4 * inch
    c.line(SIDE_MARGIN, line_y, page_width - SIDE_MARGIN, line_y)

    # --- Footer Boxes (Two Column Layout) ---
    line_y = map_y - 0.4 * inch
    c.line(SIDE_MARGIN, line_y, page_width - SIDE_MARGIN, line_y)

    gap = 0.5 * inch
    box_width = (page_width - (2 * SIDE_MARGIN) - gap) / 2
    box_height = 1.5 * inch
    box_y = line_y - box_height - 0.3 * inch

    scenario_x = SIDE_MARGIN
    summary_x = SIDE_MARGIN + box_width + gap

    # Draw two boxes
    c.rect(scenario_x, box_y, box_width, box_height)
    c.rect(summary_x, box_y, box_width, box_height)

    # --- Fill Scenario Box (Left) ---
    c.setFont("Helvetica-Bold", 10)
    c.drawString(scenario_x + 0.1 * inch, box_y + box_height - 0.2 * inch, "SCENARIO DETAILS")
    
    c.setFont("Helvetica", 9)
    detail_y = box_y + box_height - 0.4 * inch
    potential_details = [
        ("rainfall_scenario", "Rainfall Distribution"),
        ("depth_limit", "Rainfall Depth (mm)"),
        ("triangular_peak", "Peak Ratio"),
    ]
    for attr, label in potential_details:
        val = getattr(scenario, attr, "N/A")
        c.drawString(scenario_x + 0.1 * inch, detail_y, f"{label}: {val}")
        detail_y -= 0.15 * inch

   # --- Fill Risk Box (Right) ---
    c.setFont("Helvetica-Bold", 10)
    c.drawString(summary_x + 0.1 * inch, box_y + box_height - 0.2 * inch, "RISK LEVEL SUMMARY")

    # Reset text position
    text_y = box_y + box_height - 0.4 * inch
    line_height = 0.2 * inch # Increased line height for readability

    descriptions = [
        ("Low:", "Stable; minor recovery needed."),
        ("Average:", "Disruptive; requires assistance."),
        ("Strong:", "Critical; immediate intervention.")
    ]

    for title, desc in descriptions:
        # Draw Bold Label
        c.setFont("Helvetica-Bold", 8)
        c.drawString(summary_x + 0.1 * inch, text_y, title)
        
        # Draw Description with wider offset to prevent overlap
        c.setFont("Helvetica", 8)
        c.drawString(summary_x + 0.8 * inch, text_y, desc) 
        
        # Move down for next row
        text_y -= line_height

    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer