"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv 
import os

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# This maps the URL /media/ to the folder backend/api/
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'api')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!eo6(m(%%+cl4s(8@2hm(8)$lh$nqgocdv2e6$)hs$#d_&c@nc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"] # allows different people to host 


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# life time for tokens 
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'api',
    'rest_framework',
    'corsheaders',
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'flood_thesis',
        'USER': 'postgres',
        'PASSWORD': 'datateam',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

#new
CORS_ALLOW_HEADERS = [
    "authorization",
    "content-type",
    "x-csrftoken",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# change this to your directory if wala sa postgres nyo ang gdal 
# #Local files ni allycakes
# GDAL_LIBRARY_PATH = r"C:\Users\\PC\\AppData\\Local\\Programs\\OSGeo4W\\bin\\gdal312.dll"
# GEOS_LIBRARY_PATH = r"C:\\Users\\PC\\AppData\\Local\\Programs\\OSGeo4W\bin\\geos_c.dll"
# --- GIS LIBRARY CONFIGURATION ---
import os

# 1. Define the DLL paths from QGIS (These work fine for Django)
GDAL_LIBRARY_PATH = r"C:\Program Files\QGIS 3.40.4\bin\gdal310.dll"
GEOS_LIBRARY_PATH = r"C:\Program Files\QGIS 3.40.4\bin\geos_c.dll"

# 2. Fix the PROJ Version Mismatch
# We check if the virtual environment has its own proj data (usually more compatible)
VENV_PROJ = os.path.join(BASE_DIR.parent, "env", "Lib", "site-packages", "rasterio", "proj_data")
QGIS_PROJ = r"C:\Program Files\QGIS 3.40.4\share\proj"

if os.path.exists(VENV_PROJ):
    PROJ_LIB_PATH = VENV_PROJ
else:
    PROJ_LIB_PATH = QGIS_PROJ

# 3. Apply Environment Variables
os.environ["GDAL_LIBRARY_PATH"] = GDAL_LIBRARY_PATH
os.environ["GEOS_LIBRARY_PATH"] = GEOS_LIBRARY_PATH
os.environ["PROJ_LIB"] = PROJ_LIB_PATH
os.environ["GDAL_DATA"] = r"C:\Program Files\QGIS 3.40.4\share\gdal"
#Local files ni kandis
#GDAL_LIBRARY_PATH = r"C:\\Users\\PC\\AppData\\Local\\Programs\\OSGeo4W\bin\\gdal312.dll"
#GEOS_LIBRARY_PATH = r"C:\\Users\\PC\\AppData\\Local\\Programs\\OSGeo4W\bin\\geos_c.dll"

#Local files ni ck
#GDAL_LIBRARY_PATH = r"C:\Program Files\QGIS 3.40.4\bin\gdal310.dll"
#GEOS_LIBRARY_PATH = r"C:\Program Files\QGIS 3.40.4\bin\geos_c.dll"
# PROJ_LIB_PATH = r"C:\\Users\\PC\\AppData\\Local\\Programs\\OSGeo4W\\share\\proj"
# "C:\Program Files\QGIS 3.40.4\bin\proj.exe"